# Generated by Django 4.2.20 on 2025-05-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
